GET http://localhost:3000/accounts

###
POST http://localhost:3000/accounts/create-user
Content-Type: application/json

{
    "user": "Faisal",
    "password": "123456",
    "email": "faisalhawlader04@gmail.com"
}

###
POST http://localhost:3000/accounts/verify-user
Content-Type: application/json

{
    "email": "faisalhawlader04@gmail.com",
    "code": "895933"
}